@startuml

abstract Factory{
Product create()
createProduct()
registerProduct()
}

abstract Product{
use()
}

Factory <|-- IDCardFactory
class IDCardFactory{
owners
IDCard createProduct()
registerProduct()
getOwners()
}

Product <|--  IDCard
class IDCard{
owner
use()
getOwner()
}
@enduml